### ISSUE TITLE
The socket communication between pods can not be done

### ISSUE THREAD

**Issue by lmaxeniro** [Xilinx/FPGA_as_a_Service#21]
Follow the guidance I can setup all pods/service/deployment, but at last when exec command to do the communicate the below error reported, looks like the socket connection does not established--can you please help to check..
```
$ kubectl exec test-client python /opt/xilinx/k8s/client/client.py
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Traceback (most recent call last):
  File "/opt/xilinx/k8s/client/client.py", line 33, in <module>
    main()
  File "/opt/xilinx/k8s/client/client.py", line 32, in main
    client_send()
  File "/opt/xilinx/k8s/client/client.py", line 15, in client_send
    client.connect((bind_ip, bind_port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
command terminated with exit code 1
```

**Comment by yuzhang66** [comment]
@lmaxeniro 
Hi Liang, I checked in my own testing environment and it works fine. 
Can you check if the accelator-pod and fpga-server-svc are running properly?

Thanks, Yu

**Comment by lmaxeniro** [comment]
@yuzhang66 
Thanks for the reply. I delete all pods and just noticed that I may customize the server yaml incorrectly (BTW, it was checked has some syntax error if checking by yamlint tool).
After using the original yaml I can make the communication.
One more question--I find that this design will not launch the application under /server folder at all, the server be always launch up the application /opt/test folder (this looks likely coded somewhere else?)

> INFO: Reading /opt/test/vector_addition_hw.awsxclbin
> Loading: '/opt/test/vector_addition_hw.awsxclbin'

Therefore, the application (host and awsxclbin) under below folder will not be launched up at all.

> FPGA_CMD = '/opt/xilinx/k8s/server/fpga_host_exe'
> FPGA_ARG = '/opt/xilinx/k8s/server/fpga_algo.awsxclbin'

**Comment by yuzhang66** [comment]
Hi Liang, For your question:

1.Yes, it should be possible to send the request data-set to the server and receive the result from it.
2.You can find from the  aws-accelator-pod.yaml, server-side is running a bash script and loading the python server using fpga_host_exe and fpga_algo.awsxclbin. In the testing python server docker image, it doesn't contain xclbin files under folder /opt/test/.

You can check our docker image packaging tutorial and building the needed docker image for testing work.(https://github.com/Xilinx/FPGA_as_a_Service/tree/master/k8s-fpga-device-plugin/docker)

Thanks,
--Yu

**Comment by lmaxeniro** [comment]
@yuzhang66 
I think I find the reason, that in the [https://github.com/Xilinx/FPGA_as_a_Service/blob/master/k8s-fpga-device-plugin/aws-accelator-pod.yaml](url) Line 39 the command ["/opt/test/run.sh"]] should be changed to ["/opt/xilinx/k8s/server/run.sh"] . So the server python socket script can be run up when server pod created, to listen to the client pod request.
