### ISSUE TITLE
在/sys/bus/pci/devices/pci-id/目录下没有找到user_pf和mgmt_pf文件

### ISSUE THREAD

**Issue by PKUFlyingPig** [Xilinx/FPGA_as_a_Service#28]
fpga.go脚本里会根据pci设备目录下是否有user_pf文件来决定是否提取相关信息，但是我在Xilinx的FPGA对应的pci设备目录下面并没有找到这个文件，因此插件没有检测到FPGA设备。但是我通过lspci | grep Xilinx是可以看到FPGA设备的。

**Comment by yuzhang66** [comment]
请试一下设备能否被xbutil scan或者xbutil examine正确的识别到。目前device plugin对正确flash的Alveo系列运算卡进行支持,如果没有找到user_pf这个文件的话说明device应该没有正确的flash。

**Comment by PKUFlyingPig** [comment]
使用xbutil需要安装xrt软件栈，我按照https://xilinx.github.io/XRT/master/html/install.html的教程尝试在centos7上进行安装，但是执行sudo yum install xrt_<version>.rpm的时候请问version的选择在哪里看呢，我执行yum list | grep xrt 也没有找到相关的软件包。

**Comment by yuzhang66** [comment]
XRT目前并没有发布到yum软件源中
下载XRT安装包可以查看 https://www.xilinx.com/products/design-tools/vitis/xrt.html#gettingstarted
如果需要安装本地安装包可以执行 sudo yum install ./xrt_<package_version>.rpm
