### ISSUE TITLE
How can I use k8s-device-plugin to Kria Kv260

### ISSUE THREAD

**Issue by JohnsonOUO** [Xilinx/FPGA_as_a_Service#36]
I am a beginner to fpga. Today I want to use Kv260 with k8s. I have some questions.
1. Only should I change fpga.go file and Modify /dev/dri/renderDXXX ?
2. I saw https://github.com/Xilinx/FPGA_as_a_Service/issues/6#issuecomment-564838770. Someone say embedded does not have  a shell, what does this shell mean ? Is it the same about Thin shell in Zynq-7000 and ZYNQ Ultrascale+ MPSoC Based Embedded Platforms ( https://xilinx.github.io/XRT/2020.2/html/platforms.html ) If I use Kv260, can I load bitstream dynamically ?

Thanks.

**Comment by yuzhang66** [comment]
Hi Johnson, sorry for reaching you late, for your questions:
1. fpga.go is working for device scanning, you need to change it and adding the renderID(userPF) and MgmtID(mgmtPF) info into the device struct, and you may also need to change the device register and allocate logic in file server.go
2. Currently the device plugin is a solution for Alveo cards, as the link you followed, there's no shell for the embedded platform, and kv260 can not load the bitstream dynamically. You could check with the Kv260 support team for more detailed info.
