### ISSUE TITLE
Run hello world in the pod没有得到输出。

### ISSUE THREAD

**Issue by llt19903767731** [Xilinx/FPGA_as_a_Service#9]
前面的部署过程都没有问题，到最后运行Run hello world in the pod时，输出如下：
root@mypod:~# source /opt/xilinx/xrt/setup.sh
XILINX_XRT      : /opt/xilinx/xrt
PATH            : /opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH : /opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:
root@mypod:~# xbutil scan
INFO: Found total 1 card(s), 1 are usable
[0]mgmt:[02:00.0]:0x5000:0x000e:[xclmgmt:2.3.1301,192e706aea53163a04c574f9b3fe9ed76b6ca471:512]
[0]user:[02:00.1]:0x5001:0x000e:[xocl:2.3.1301,192e706aea53163a04c574f9b3fe9ed76b6ca471:129]
root@mypod:~# cd /tmp/alveo-u200/xilinx_u200_xdma_201830_1/test/
root@mypod:/tmp/alveo-u200/xilinx_u200_xdma_201830_1/test# ls -al
total 88120
drwxr-xr-x 1 root root     4096 Dec 25 05:48 .
drwxr-xr-x 1 root root     4096 Apr 16  2019 ..
-r--r--r-- 1 root root 50632826 Apr 16  2019 bandwidth.xclbin
-r--r--r-- 1 root root    29256 Apr 16  2019 kernel_bw.exe
-rwxrwxrwx 1 root root    22744 Apr 16  2019 validate.exe
-rwxrwxrwx 1 root root 39523869 Apr 16  2019 verify.xclbin
root@mypod:/tmp/alveo-u200/xilinx_u200_xdma_201830_1/test# ./validate.exe ./verify.xclbin 

Platform information
Platform name:       Xilinx
Platform version:    OpenCL 1.0
Platform profile:    EMBEDDED_PROFILE
Platform extensions: cl_khr_icd

Found 1 compute devices!:
loading ./verify.xclbin

ERROR: Failed to load xclbin.
Error: Failed to create compute program!
在/tmp/alveo-u200/xilinx_u200_xdma_201830_1/test目录下，并没有找到verify.exe文件，从docker hub上拉取的也是最新的镜像，于是我执行的是 /validate.exe ./verify.xclbin 但输出结果并没有hello world部分，可以帮忙看一下吗？谢谢

**Comment by durgabhavaniv** [comment]
I have same error
